
package webservice.sync;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISoftSync", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISoftSync {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.sync.SoftSyncResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "softSync", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/", className = "webservice.sync.SoftSync")
    @ResponseWrapper(localName = "softSyncResponse", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/", className = "webservice.sync.SoftSyncResponse")
    public webservice.sync.SoftSyncResponse.Return softSync(
        @WebParam(name = "arg0", targetNamespace = "")
        List<SoftSyncParam> arg0);

}
