
package webservice.sync;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoftSyncService", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/", wsdlLocation = "http://localhost:8080/softStock/softSync?wsdl")
public class SoftSyncService
    extends Service
{

    private final static URL SOFTSYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOFTSYNCSERVICE_EXCEPTION;
    private final static QName SOFTSYNCSERVICE_QNAME = new QName("http://softOrder.dsp.cma.dtdream.com/", "SoftSyncService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/softStock/softSync?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOFTSYNCSERVICE_WSDL_LOCATION = url;
        SOFTSYNCSERVICE_EXCEPTION = e;
    }

    public SoftSyncService() {
        super(__getWsdlLocation(), SOFTSYNCSERVICE_QNAME);
    }

    public SoftSyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOFTSYNCSERVICE_QNAME, features);
    }

    public SoftSyncService(URL wsdlLocation) {
        super(wsdlLocation, SOFTSYNCSERVICE_QNAME);
    }

    public SoftSyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOFTSYNCSERVICE_QNAME, features);
    }

    public SoftSyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoftSyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoftSync
     */
    @WebEndpoint(name = "SoftSyncPort")
    public ISoftSync getSoftSyncPort() {
        return super.getPort(new QName("http://softOrder.dsp.cma.dtdream.com/", "SoftSyncPort"), ISoftSync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoftSync
     */
    @WebEndpoint(name = "SoftSyncPort")
    public ISoftSync getSoftSyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://softOrder.dsp.cma.dtdream.com/", "SoftSyncPort"), ISoftSync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOFTSYNCSERVICE_EXCEPTION!= null) {
            throw SOFTSYNCSERVICE_EXCEPTION;
        }
        return SOFTSYNCSERVICE_WSDL_LOCATION;
    }

}
