
package com.dtdream.cma.dsp.softorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISoftPrice", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISoftPrice {


    /**
     * 
     * @param softwarePartNo
     * @param customerNumber
     * @return
     *     returns com.dtdream.cma.dsp.softorder.SoftPriceBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "softPrice", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/", className = "com.dtdream.cma.dsp.softorder.SoftPrice")
    @ResponseWrapper(localName = "softPriceResponse", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/", className = "com.dtdream.cma.dsp.softorder.SoftPriceResponse")
    public SoftPriceBean softPrice(
        @WebParam(name = "softwarePartNo", targetNamespace = "")
        String softwarePartNo,
        @WebParam(name = "customerNumber", targetNamespace = "")
        String customerNumber);

}
