
package com.dtdream.cma.dsp.softorder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoftPriceService", targetNamespace = "http://softOrder.dsp.cma.dtdream.com/", wsdlLocation = "http://localhost:8080/softStock/softPrice?wsdl")
public class SoftPriceService
    extends Service
{

    private final static URL SOFTPRICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOFTPRICESERVICE_EXCEPTION;
    private final static QName SOFTPRICESERVICE_QNAME = new QName("http://softOrder.dsp.cma.dtdream.com/", "SoftPriceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/softStock/softPrice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOFTPRICESERVICE_WSDL_LOCATION = url;
        SOFTPRICESERVICE_EXCEPTION = e;
    }

    public SoftPriceService() {
        super(__getWsdlLocation(), SOFTPRICESERVICE_QNAME);
    }

    public SoftPriceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOFTPRICESERVICE_QNAME, features);
    }

    public SoftPriceService(URL wsdlLocation) {
        super(wsdlLocation, SOFTPRICESERVICE_QNAME);
    }

    public SoftPriceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOFTPRICESERVICE_QNAME, features);
    }

    public SoftPriceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoftPriceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISoftPrice
     */
    @WebEndpoint(name = "SoftPricePort")
    public ISoftPrice getSoftPricePort() {
        return super.getPort(new QName("http://softOrder.dsp.cma.dtdream.com/", "SoftPricePort"), ISoftPrice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISoftPrice
     */
    @WebEndpoint(name = "SoftPricePort")
    public ISoftPrice getSoftPricePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://softOrder.dsp.cma.dtdream.com/", "SoftPricePort"), ISoftPrice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOFTPRICESERVICE_EXCEPTION!= null) {
            throw SOFTPRICESERVICE_EXCEPTION;
        }
        return SOFTPRICESERVICE_WSDL_LOCATION;
    }

}
